#!/usr/bin/env bash

# File permissions for templates.
# In the same format as chmod.
# `chmod "${perms[EXT]}" file.EXT` will be performed.
perms=(
  [py]=755
  [sh]=+x
# [EXT]=PERMS
)
export perms

# Set the content of the variables here
# To add a new line, just put a carriage
# return in the quotes. \n does not work.
DATE=$(date +"%d %B %Y")
export DATE
export AUTHOR="Rodolphe Thienard"
export CPP_HEADER="#include <iostream>"
export C_HEADER="#include <stdio.h>"
export MAKE_CC="gcc"
export MAKE_CFLAGS="-Wall -g -Werror -pedantic"
